### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by sagartalla** [microsoft/vscode-remote-try-java#47]
Mac  13-inch, Mid 2012
OSX 10.11.6 

Docker Version 18.06.1-ce-mac73 (26764)

```
Sending build context to Docker daemon  772.6kB
Step 1/4 : FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.14
 ---> 29fbad96cc78
Step 2/4 : RUN apk add --no-cache       nodejs  npm     make    g++     docker-cli      docker-compose  ;
 ---> Using cache
 ---> 166a432e844c
Step 3/4 : RUN cd && npm i node-pty
 ---> Running in dfa03b615fba
npm ERR! code 1
npm ERR! path /root/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! make: Entering directory '/root/node_modules/node-pty/build'
npm ERR! make: Leaving directory '/root/node_modules/node-pty/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.20.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v14.20.0/node-v14.20.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.20.0/node-v14.20.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v14.20.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.20.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.20.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.20.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.20.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: printf: Operation not permitted
npm ERR! make: *** [pty.target.mk:107: Release/obj.target/pty/src/unix/pty.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
npm ERR! gyp ERR! System Linux 4.9.93-linuxkit-aufs
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /root/node_modules/node-pty
npm ERR! gyp ERR! node -v v14.20.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-10T13_57_40_459Z-debug.log
The command '/bin/sh -c cd && npm i node-pty' returned a non-zero code: 1
[7024 ms] Command failed: docker build -f /var/folders/gb/x6z336p540z29919w2fqhv1h0000gn/T/vsch/bootstrap-image/0.245.2/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/gb/x6z336p540z29919w2fqhv1h0000gn/T/vsch/bootstrap-image/0.245.2
[7024 ms] Exit code 1
```

**Comment by sagartalla** [comment]
downgrade node version  `"NODE_VERSION": "14.16.1"` in devcontainer.json
